# Generated by Django 4.1.7 on 2023-04-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('ciudad', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('ingreso', models.DateTimeField()),
                ('alta', models.DateTimeField()),
                ('historial_clinico', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='instrumentos',
        ),
    ]
